name: Lambda Worflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FUNCTION_NAME: "tastytap-auth"

jobs:
  deploy:
    name: "Deploying lambda"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Compressing files
        run: zip -r lambda.zip node_modules index.js

      - name: Deploying lambda
        run: aws lambda update-function-code --function-name=${{ env.FUNCTION_NAME }} --zip-file=fileb://lambda.zip